# Script for CI/CD on gitlab instances.
#
image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev make rsync
  - cd docgen 
  - pip install -r requirements.txt
  - pip install pygame  # required by importing flipdotsim
  - make html
  - mv _build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
